# frozen_string_literal: true

# Gemfile for a standard Rack application
source "https://rubygems.org"

ruby "3.4.1"

gem "debug", require: false
gem "fast-mcp"
gem "puma"
gem "rack"
gem "rackup"
gem "rubocop", require: false
